AllCops:
  TargetRubyVersion: 2.7.1
  NewCops: enable

inherit_from:
  - .rubocop_todo.yml

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
